"""empty message

Revision ID: 9438df22c978
Revises: 6fd1ba5a450c
Create Date: 2022-10-20 23:03:47.538261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9438df22c978'
down_revision = '6fd1ba5a450c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
