"""empty message

Revision ID: 98e43abd3df6
Revises: e890a740fa69
Create Date: 2022-10-20 23:15:20.296251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e43abd3df6'
down_revision = 'e890a740fa69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'card', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'book_id')
    op.drop_column('card', 'user_id')
    # ### end Alembic commands ###
