"""empty message

Revision ID: e890a740fa69
Revises: 9438df22c978
Create Date: 2022-10-20 23:12:37.610588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e890a740fa69'
down_revision = '9438df22c978'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
